# Generated by Django 3.0.2 on 2020-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(default='Bachelors', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.IntegerField(default=0),
        ),
    ]
