# Generated by Django 3.0.2 on 2020-02-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200201_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='URSB_registration_Number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_owner',
        ),
    ]
