# Generated by Django 3.0.3 on 2020-03-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
