# Generated by Django 3.0.2 on 2020-01-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='default.jpg', upload_to='')),
                ('location', models.TextField()),
                ('room_sizes', models.IntegerField()),
                ('bed_sizes', models.IntegerField()),
                ('has_canteen', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('room_cleaning_services', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('self_contained', models.BooleanField(default=False)),
                ('cable_tv', models.BooleanField(default=False)),
                ('has_shuttle', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('image1', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('image2', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('image3', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('image4', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('image5', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('has_water', models.BooleanField(default=False)),
                ('established', models.DateTimeField()),
                ('renovation_frequency', models.CharField(max_length=50)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
