# Generated by Django 3.0.2 on 2020-01-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='Owner',
            new_name='owner',
        ),
    ]
