# Generated by Django 3.0.2 on 2020-02-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20200131_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='title',
            new_name='hostel_name',
        ),
    ]
