# Generated by Django 3.0.2 on 2020-02-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_auto_20200201_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='renovation_frequency',
        ),
        migrations.AddField(
            model_name='hostel',
            name='image6',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
    ]
