# Generated by Django 3.0.2 on 2020-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_auto_20200201_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
    ]
