# Generated by Django 3.0.3 on 2020-03-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='bed_sizes',
            new_name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='cable_tv',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='established',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='has_water',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='room_sizes',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='self_contained',
        ),
        migrations.AddField(
            model_name='hostel',
            name='booking_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='double_room_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='single_room_price',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='A1', max_length=50)),
                ('type', models.CharField(default='single', max_length=50)),
                ('room_sizes', models.IntegerField(default='20 x 20')),
                ('bed_sizes', models.IntegerField(default='6 x 6')),
                ('self_contained', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.Hostel')),
            ],
        ),
    ]
