# Generated by Django 3.0.3 on 2020-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0007_auto_20200320_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='id',
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_id',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
