# Generated by Django 3.0.3 on 2020-03-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0008_auto_20200323_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_id',
            field=models.CharField(default='null', max_length=10, primary_key=True, serialize=False),
        ),
    ]
