# Generated by Django 3.0.3 on 2020-03-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0010_auto_20200323_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='id',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_id',
            field=models.CharField(default='null', max_length=10, primary_key=True, serialize=False),
        ),
    ]
