# Generated by Django 3.0.3 on 2020-03-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0011_auto_20200323_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='hostel_id',
            new_name='hostel_unique_identifier',
        ),
    ]
